FROM node:latest as build

WORKDIR /user/local/app
COPY ./ /user/local/app

RUN npm install
RUN npm run build


FROM nginx:latest

COPY --from=build /user/local/app/dist/musicweb /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4200